/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blotter-guide`; params?: Router.UnknownInputParams; } | { pathname: `/broadcasts`; params?: Router.UnknownInputParams; } | { pathname: `/edit-report`; params?: Router.UnknownInputParams; } | { pathname: `/follow-up`; params?: Router.UnknownInputParams; } | { pathname: `/hotlines`; params?: Router.UnknownInputParams; } | { pathname: `/my-reports`; params?: Router.UnknownInputParams; } | { pathname: `/report-success`; params?: Router.UnknownInputParams; } | { pathname: `/../admin-web/src/pages/AuditLogs`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report` | `/report`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/blotter-guide`; params?: Router.UnknownOutputParams; } | { pathname: `/broadcasts`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-report`; params?: Router.UnknownOutputParams; } | { pathname: `/follow-up`; params?: Router.UnknownOutputParams; } | { pathname: `/hotlines`; params?: Router.UnknownOutputParams; } | { pathname: `/my-reports`; params?: Router.UnknownOutputParams; } | { pathname: `/report-success`; params?: Router.UnknownOutputParams; } | { pathname: `/../admin-web/src/pages/AuditLogs`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/report` | `/report`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/blotter-guide${`?${string}` | `#${string}` | ''}` | `/broadcasts${`?${string}` | `#${string}` | ''}` | `/edit-report${`?${string}` | `#${string}` | ''}` | `/follow-up${`?${string}` | `#${string}` | ''}` | `/hotlines${`?${string}` | `#${string}` | ''}` | `/my-reports${`?${string}` | `#${string}` | ''}` | `/report-success${`?${string}` | `#${string}` | ''}` | `/../admin-web/src/pages/AuditLogs${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/report${`?${string}` | `#${string}` | ''}` | `/report${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blotter-guide`; params?: Router.UnknownInputParams; } | { pathname: `/broadcasts`; params?: Router.UnknownInputParams; } | { pathname: `/edit-report`; params?: Router.UnknownInputParams; } | { pathname: `/follow-up`; params?: Router.UnknownInputParams; } | { pathname: `/hotlines`; params?: Router.UnknownInputParams; } | { pathname: `/my-reports`; params?: Router.UnknownInputParams; } | { pathname: `/report-success`; params?: Router.UnknownInputParams; } | { pathname: `/../admin-web/src/pages/AuditLogs`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report` | `/report`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; };
    }
  }
}
